# Generated by Django 3.0.4 on 2020-05-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200405_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_adclient',
            field=models.BooleanField(default=False),
        ),
    ]
