# Generated by Django 3.0.4 on 2020-03-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adtool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='genre',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='url_link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('sleeping', 'SLEEPING'), ('banner', 'BANNER'), ('popup', 'POPUP')], default='sleeping', max_length=10),
        ),
    ]
