# Generated by Django 3.0.4 on 2020-03-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adtool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='genre',
            field=models.CharField(default='', max_length=30),
        ),
    ]
