# Generated by Django 3.0.4 on 2020-03-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adtool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='category',
            field=models.CharField(default='sleeping', max_length=10),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
