# Generated by Django 3.0.4 on 2020-03-27 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200325_2303'),
        ('adtool', '0002_auto_20200327_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
