# Generated by Django 3.0.4 on 2020-03-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adtool', '0002_advertisement_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='url_link',
            field=models.URLField(default=''),
        ),
    ]
