# Generated by Django 3.0.4 on 2020-03-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adtool', '0003_advertisement_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='genre',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
