# Generated by Django 3.0.4 on 2020-04-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adtool', '0005_auto_20200327_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userKey', models.TextField(default='00000000000000000000000000000000', max_length=32)),
            ],
        ),
    ]
