# Generated by Django 3.0.4 on 2020-04-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adtool', '0007_auto_20200402_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementclient',
            name='userKey',
            field=models.TextField(default='00000000000000000000000000000000', max_length=32),
        ),
    ]
