# Generated by Django 3.0.4 on 2020-04-16 14:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adtool', '0008_auto_20200402_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='AdvertisementLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_date', models.DateTimeField(verbose_name='date clicked')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adtool.Advertisement')),
            ],
        ),
    ]
