# Generated by Django 3.0.4 on 2020-04-30 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adtool', '0009_auto_20200416_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='ad_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='genre',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='size',
            field=models.CharField(choices=[('medium rectangle', '300x250 pixels'), ('large rectangle', '336x280 pixels'), ('leaderboard', '728x90 pixels'), ('half page', '320x100 pixels'), ('free size', 'free size')], default='free size', max_length=16),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='advertisementlog',
            name='click_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date clicked'),
        ),
    ]
