# Generated by Django 3.0.4 on 2020-05-13 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addisplay', '0004_auto_20200511_1945'),
        ('adtool', '0011_auto_20200511_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementlog',
            name='site',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.PROTECT, to='addisplay.Website'),
        ),
    ]
