# Generated by Django 3.0.4 on 2020-05-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adtool', '0013_auto_20200513_2051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvertisementClient',
        ),
    ]
