# Generated by Django 3.0.4 on 2020-05-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addisplay', '0002_auto_20200511_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='userkey',
            field=models.CharField(max_length=32),
        ),
    ]
