# Generated by Django 3.0.4 on 2020-05-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addisplay', '0006_auto_20200513_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvertisementClient',
        ),
    ]
